spring.application.name=crm-service

spring.datasource.url=jdbc:mysql://localhost:3306/crm_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

auth.secret-key=solsticecoffee.ph127897asdkjal6-aksdjlafjsgsd0-f9adalka;sf=
encryption.salt=secretkeyngsolsticecoffee1234567890